### ISSUE TITLE
Roadmap to doctree v1.0

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/doctree#27]
## State of doctree today: pre v0.1

We're working towards v0.1, and are only a few weeks into development.

* [x] [Binary releases](https://github.com/sourcegraph/doctree#installation) for every OS
* [x] [Docker images](https://github.com/sourcegraph/doctree#installation) you can self-host
* [x] Basic search navigation experience
* Basic support for
  * [ ] Go (missing vars/consts/etc, only functions working today)
  * [ ] Python (missing vars/consts/etc, only functions working today)
  * [ ] Markdown (missing search integration, ability to link to headers)

## Major milestones coming soon

* [ ] #18
* [ ] #11
* [ ] #12
* [ ] #19
* [ ] #15
* [ ] #21

**Comment by slimsag** [comment]
@DaivikDave I'd love that! Right now Go and Python indexers are pretty active, maybe you'd like to work on creating a new indexer for a new language, though? You can probably easily copy the Python one right now to get started - and see https://github.com/sourcegraph/doctree/issues/10 for some resources on how it all works.

A JS/TS one, Java one, etc. would be very cool. Or if you want to help in other places let me know. Also join the Discord :)

**Comment by DaivikDave** [comment]
@slimsag Thanks. I would to work on language support for javascript. I'll go through the language support issue to get started and join discord!
